[tools]
bun = "latest"
deno = "latest"
node = "lts"
rust = "latest"
go = "latest"
ruby = "3.4"
python = "latest"

# 以下のコマンドでインストールする必要がある。
# HP_CONFIGURE_OPTIONS="--with-openssl=$(brew --prefix openssl) --with-iconv=$(brew --prefix libiconv)" mise install
# see: https://github.com/asdf-community/asdf-php/issues/163#issuecomment-2518719651
# php = "8.5"

uv = "latest"
terraform = "latest"

"npm:pnpm" = "latest"
"npm:yarn" = "1.22.22"
"npm:serve" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"npm:@github/copilot" = "latest"
