[tools]
bun = "latest"
deno = "latest"
node = "lts"
rust = "latest"
go = "latest"
ruby = "3.4"
python = "latest"
php = "8.5"

uv = "latest"
terraform = "latest"

"npm:pnpm" = "latest"
"npm:yarn" = "1.22.22"
"npm:serve" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"npm:@github/copilot" = "latest"
